name       : k3b
version    : 20.12.2
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/k3b-20.12.2.tar.xz : 8fa4def0d8c4c62b6860ffe5ca0e67a121d94ef99823465e5b7a5a7345460f3f
homepage   : https://kde.org/applications/multimedia/org.kde.k3b
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.multimedia
summary    : K3b - The CD Kreator
description: |
    Full-featured CD/DVD/Blu-ray burning and ripping application.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(libavformat)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - karchive-devel
    - kcmutils-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - lame-devel
    - libkcddb-devel
    - libmad-devel
rundeps    :
    - cdrdao
    - cdrtools
    - dvd_rw-tools
    - sox
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
