name       : k3b
version    : 21.08.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/k3b-21.08.2.tar.xz : 2d57b2fa3f1c7982d056d210c9a6518f46d6638e295706df6859794de77f3dbd
homepage   : https://kde.org/applications/multimedia/org.kde.k3b
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.multimedia
summary    : K3b - The CD Kreator
description: |
    Full-featured CD/DVD/Blu-ray burning and ripping application.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(libavformat)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - karchive-devel
    - kcmutils-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - lame-devel
    - libkcddb-devel
    - libmad-devel
rundeps    :
    - cdrdao
    - cdrtools
    - dvd_rw-tools
    - sox
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
