name       : k3b
version    : 20.08.3
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/k3b-20.08.3.tar.xz : 9d81f1b859dca68a781903f35b3186a9864222c8bb2c85cd7e9481d79eb9e261
homepage   : https://kde.org/applications/multimedia/org.kde.k3b
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.multimedia
summary    : K3b - The CD Kreator
description: |
    Full-featured CD/DVD/Blu-ray burning and ripping application.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(libavformat)
    - pkgconfig(libmusicbrainz5)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - ki18n-devel
    - kiconthemes-devel
    - kjobwidgets-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - lame-devel
    - libkcddb-devel
    - libmad-devel
    - shared-mime-info
    - solid-devel
rundeps    :
    - cdrdao
    - cdrtools
    - dvd_rw-tools
    - sox
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
